spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    gcp:
      pubsub:
        emulator-host: localhost:8085
        project-id: test-project
  threads:
    virtual:
      enabled: true